SHELL = /bin/bash
JOBS=2

UAUSER="usbarmory"
UAHOSTNAME="usbarmory"

VGNAME="uaVG"

# https://servers.opennicproject.org/
NAMESERVER=185.121.177.177
# set to blank if you want journaling, default: " -O ^has_journal "
EXT4WITHOUTJOURNAL= -O ^has_journal 
# set to blank to use mirrors directly, don't forget to put a trailing slash otherwise --> http://".../"MIRROR
APTCACHERNGURL=localhost:3142/
GADGETMOD="g_ether"
GADGETOPTS="options g_ether use_eem=0 dev_addr=1a:55:89:a2:69:41 host_addr=1a:55:89:a2:69:42"

LINUX_VER=4.9.51
UBOOT_VER=2017.05

PKGS2BOOTSTRAP_DEBIAN=ssh,sudo,ntpdate,fake-hwclock,openssl,vim,nano,cryptsetup,lvm2,locales,less,cpufrequtils,isc-dhcp-server,haveged,whois,iw,wpasupplicant,dbus
PKGS2BOOTSTRAP_DEVUAN=ssh,sudo,ntpdate,fake-hwclock,openssl,vim,nano,cryptsetup,lvm2,locales,less,cpufrequtils,isc-dhcp-server,haveged,whois,iw,wpasupplicant,dbus,tlsdate,dropbear,initramfs-tools,kbd,u-boot-tools,console-setup,busybox

USBARMORY_REPO=https://raw.githubusercontent.com/inversepath/usbarmory/master
MXC_SCC2_REPO=https://github.com/inversepath/mxc-scc2
TARGET_IMG?=usbarmory-devuan_jessie-base_image-$(shell date +%Y%m%d).raw

KEYFILE=${CURDIR}/luks.keyfile
LUKSMAP=usbarmory-base_image-luks

