#!/bin/sh -e

if [ "$1" != configure ]; then
    exit 0
fi

ROOTDEV=$(findmnt -n -o SOURCE --target /boot/zImage-YYYY-usbarmory)
sed -i -e 's@__FIXME_ROOTDEV__@'"$ROOTDEV"'@' /boot/armory-boot.conf /boot/armory-boot-nonsecure.conf
